export { Data } from './Data'
export { Home } from './Home'
export { Perfil } from './Perfil'
export { MiPerfil} from './MiPerfil'
export { NotFound } from './NotFound'
export { PostSearch } from './PostSearch'